[package]
name = "yew-hello-world"
version = "0.1.0"
edition = "2021"

[dependencies]
gloo-console = "0.3"
yew = { git = "https://github.com/yewstack/yew/", features = ["csr"] }
serde = { version="1.0" }
